//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SaidyakovLanguage
{
    using System;
    using System.Collections.Generic;
    using System.Linq;

    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.ClientService = new HashSet<ClientService>();
            this.Tag = new HashSet<Tag>();
        }
        public string FIO
        {
            get
            {
                return this.FirstName + " " + this.LastName + " " + this.Patronymic;
            }
        }

        public string GenderName
        {
            get
            {
                if (GenderCode == "2") return "Мужской";
                return "Женский";
            }
        }
        public string BirthdayText
        {
            get
            {
                return this.Birthday.ToShortDateString();
            }
        }

        public string RegistrationDateText
        {
            get
            {
                return this.RegistrationDate.ToShortDateString();
            }
        }

        public string LastVisit
        {
            get
            {
                return this.ClientService.Max(p => p.StartTime).ToShortDateString();
            }
        }
        
        public string LastVisitText
        {
            get
            {
                if (VisitCount == 0)
                {
                    return "Дата последнего посещения: " + "нет ";
                }

                return "Дата последнего посещения: " + LastVisit + " ";
            }
        }

        public int VisitCount
        {
            get
            {
                return this.ClientService.Count();
            }
        }

        public string VisitCountText
        {
            get
            {
                return "Кол-во посещений: " + VisitCount;
            }
        }
        public DateTime StartTimeDT
        {
            get
            {

                if (VisitCount == 0) {
                    return DateTime.MinValue; 
                }
                return ClientService.Max(x => x.StartTime);
            }
        }

        public string StartTime
        {
            get
            {
                if (VisitCount == 0) {
                    return "Нет"; 
                }
                return ClientService.Max(x => x.StartTime).ToShortDateString();
            }
        }
        
        public int ID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Patronymic { get; set; }
        public string GenderCode { get; set; }
        public string Phone { get; set; }
        public string PhotoPath { get; set; }
        public System.DateTime Birthday { get; set; }
        public string Email { get; set; }
        public System.DateTime RegistrationDate { get; set; }
    
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ClientService> ClientService { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tag> Tag { get; set; }
    }
}
